analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: Schleswig-Holstein
  adjective: Schleswig-Holstein
create_goals:
  previous_next_links: false
  goals: []
create_indicators:
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: 
  - type: standard
    language: de
    format: "%d %Y %m"
disclaimer:
  phase: ''
  message: ''
  hidden: true
email_contacts:
  questions: nhbericht@stk.landsh.de
  suggestions: nhbericht@stk.landsh.de
  functional: nhbericht@stk.landsh.de
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  # - path: 'https://twitter.com/MyTwitterAccount'
  #   translation_key: general.twitter
  # - path: 'https://facebook.com/MyFacebookAccount'
  #   translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Gemeinschaftswerk Nachhaltigkeit
    content: |
      <img src="assets/img/logo.png"> Die Landesregierung Schleswig-Holstein ist Initiator beim Gemeinschaftswerk Nachhaltigkeit.
    include: ''
    button_label: Mehr erfahren
    button_link: 'https://gemeinschaftswerk-nachhaltigkeit.de/app/organisations/1713'
    rule_color: ''
  - title: 17 Ziele
    content: |
      Alles über die 17 Ziele der Nachhaltigkeit finden Sie hier.
    include: ''
    button_label: Mehr erfahren
    button_link: 'https://17ziele.de'
    rule_color: ''
frontpage_goals_grid:
  title: frontpage.heading_short
  description: frontpage.instructions_shorter
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - de
languages_public: []
logos: []
map_layers: []
map_options:
  disaggregation_controls: false
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: ''
menu:
  - path: /
    translation_key: general.home
    dropdown: []
  # - path: /goals
  #  translation_key: general.goals
  #  dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  # - path: /news
  #  translation_key: menu.updates
  #  dropdown: []
  # - path: /faq
  #  translation_key: menu.faq
  #  dropdown: []  
  # - path: /about
  #  translation_key: menu.about
  #  dropdown: []    
metadata_edit_url: metadata
metadata_tabs:
  - scope: publications
    title: 'Informationen zum Indikator'
    description: 'Informationen und weitere Details zum Indikator, veröffentlicht im Nachhaltigkeitsbericht des Landes Schleswig-Holstein, finden Sie hier:'
    placeholder: 'Noch keine weiteren Infos hinterlegt.'
  #- scope: national
  #  title: indicator.national_metadata
  #  description: indicator.national_metadata_blurb
  # - scope: global
  #  title: indicator.global_metadata
  #  description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
news:
  category_links: false
progress_status:
  status_heading: ''
  status_types: []
remote_data_prefix: https://land-schleswig-holstein.github.io/osdg-data/
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: https://github.com/Land-Schleswig-Holstein/osdg-data
repository_url_site: https://github.com/Land-Schleswig-Holstein/nachhaltigkeitsbericht
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
validate_indicator_config: false
validate_site_config: true
x_axis_label: ''
# Konfiguration
use_new_config_forms: true
indicator_metadata_form:
  enabled: true
  translated: false
